### ISSUE TITLE
[BUG] Authentication for this request failed. error for accessing non-US environments 

### ISSUE THREAD

**Issue by LinnZawWin** [cloudsmithconsulting/cds-for-code#10] opened 2020-02-10 02:54 UTC
**Describe the bug**
CDS Explorer is not able to load the solutions from non-US environment (tested with xxx.crm6.dynamics.com) even though adding the connection and selecting the environment is working fine.

**To Reproduce**
1. Open CDS Explorer
2. Create New CDS Connection for non-US environment (e.g. xxx.crm6.dynamics.com)
3. Enter the credentials and Discover
4. Select the environment
5. Save the connection
6. Expand the newly created connection in the CDS explorer
7. Expand the environment in that connect.
8. There will be an error "Authentication for this request failed." as in the screenshot below.
9. Check the error log in OUTPUT of VS Code.

**Expected behavior**
After expanding the CDS Connection and expanding the environment, CDS Explorer should show the Solutions and Applications folder of that environment. (just like how it is working for US environments xxx.crm.dynamics.com.

**Screenshots**
Error Message
![Error Message](https://user-images.githubusercontent.com/14156926/74117294-14cd1000-4c1c-11ea-9fe1-47e359330016.png)

Failed non-US Environment just showing Loading circle
![Environment Loading](https://user-images.githubusercontent.com/14156926/74117389-58277e80-4c1c-11ea-93ef-2ef92745b212.png)

**Additional context**
Output log of successful and failed connections

[03:11:36]: View: cs.cds.viewContainers.cdsExplorer.createEntries: Element 'US ENV' is loading child entries.
[03:11:36]: HTTP GET https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances?$filter=Url%20eq%20%27https%3A%2F%2Fusenvironment.crm.dynamics.com%27 (statusCode: 200, out: 0b, in: 677b, time: 340ms)
[03:11:36]: View: cs.cds.viewContainers.cdsExplorer.createEntries: Element 'US ENV' loaded child entries.  Parsed 1/1 entries (total: 347ms, retreive: 343ms;98.8%, parse: 4ms;1.2%)
[03:11:41]: HTTP GET https://usenvironment.api.crm.dynamics.com/api/data/v9.1/solutions?$select=solutionid,uniquename,friendlyname,version,ismanaged,isvisible&$filter=uniquename%20eq%20%27Active%27&$orderby=uniquename (statusCode: 200, out: 0b, in: 354b, time: 3939ms)

[03:11:44]: View: cs.cds.viewContainers.cdsExplorer.createEntries: Element 'AUS ENV' is loading child entries.
[03:11:44]: HTTP GET https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances?$filter=Url%20eq%20%27https%3A%2F%2Fausenvironment.crm6.dynamics.com%27 (statusCode: 200, out: 0b, in: 678b, time: 295ms)
[03:11:44]: View: cs.cds.viewContainers.cdsExplorer.createEntries: Element 'AUS ENV' loaded child entries.  Parsed 1/1 entries (total: 298ms, retreive: 297ms;99.7%, parse: 1ms;0.3%)
[03:11:46]: OAuth: removing existing token and attempting re-authentication flow.
[03:11:46]: OAuth: HTTP 401 received

**Comment by CloudSmithIra** [comment] 2020-02-10 15:19
Thank you for your detailed bug report. We have this on the backlog now and will begin diagnosis this sprint.

**Comment by CloudSmithBrandon** [comment] 2020-02-10 17:10
Hello,

We've been investigating this issue and have not yet been able to correlate it with telemetry tracking login failures.  If you could provide us with a little more information, it should help us determine the cause of this issue:

1. When you re-start VSCode, are you able to successfully expand the node for the .crm6.dynamics.com instance?  (This will let us know if it's an issue with the local state of the view or not)
2. Does the account you're using to register your .crm6.dynamics.com connection use MFA (multi-factor authentication)?
3. What is your OS/VSCode version?

We will attempt to reproduce this issue internally and update shortly.

Thanks,
Brandon

**Comment by LinnZawWin** [comment] 2020-02-11 10:17
1. When I re-start VSCode, I am not even able to expand the first connection node. (previously, I was able to expand the node for the connection but not for the environment (2nd) node)
![image](https://user-images.githubusercontent.com/14156926/74227846-2dc0e880-4d24-11ea-990e-f417a73d6baf.png)

2. The account I'm using to register my .crm6.dynamics.com connection **does not use** MFA (multi-factor authentication)

3. OS version: Windows 10 Version 1909 Build 18363.592
VSCode version: 1.42.0

**Comment by CloudSmithBrandon** [comment] 2020-02-11 13:20
Thank you, this is helpful.  We're very sorry you've been having this experience.  This is certainly an odd behavior that we haven't seen before.  Here's how I'd like to proceed.

1. We will build a repro of this scenario using a trial tenant in Aus/NZ (crm6.dynamics.com)
2. If we can repro, then we'll update this with the status of a fix.  
3. If we can't, and if you're willing, I'd like to have you run a debug build of the extension using screen sharing so that we can evaluate this scenario with you interactively.  My team and/or I would be happy to setup a time to work with you in your local time zone (NZ).  Given the time difference (we are Eastern US time zone), this would likely be earlier in your day.

I will update the status of this issue today with our findings from the repo using the trial tenant in your Geo.

**Comment by LinnZawWin** [comment] 2020-02-11 22:00
Sounds like a plan. I'm happy to run a debug build of the extension using screen sharing.

**Comment by CloudSmithBrandon** [comment] 2020-02-11 23:40
Hi @LinnZawWin ,

We were able to reproduce this issue using a trial tenant in the APAC region (specifically, we requested the tenant in New Zealand).  This does appear to be localized to the region, and we apologize for the trouble.  

My team and I are working on a fix that will drop with the 0.9.0 build.  After the fix is ready, I can share a private build with you to evaluate/verify the fix works in your scenario, or we can share instructions on how to download and build/run the fix from GitHub.  Please email [support@cdsforcode.com](mailto:support@cdsforcode.com) and reference [GitHub Issue #10](https://github.com/cloudsmithconsulting/cds-for-code/issues/10) and a link to the build will be emailed back to you when it is ready.

Thank you for offering the time to work with us on a repro.  At this point, since we are able to reproduce this issue in-house, I do not believe it will be necessary to schedule a screen sharing session.  

Regards,
Brandon

**Comment by CloudSmithBrandon** [comment] 2020-02-13 21:17
Hi @LinnZawWin and others,

Given the severity of this issue, we've gone ahead and pushed the fix (and a related set of fixes) to the 0.8.12 release on the VSCode Marketplace.  Please update your extension to this version (Extension > CDS for Code > Update) and attempt to re-connect.

If you had already saved this connection, it may be necessary to remove and re-add the connection.  We apologize for the inconvenience.  Please let us know if you continue to experience issues.

**Closed as completed by CloudSmithBrandon** 2020-02-13 21:17 UTC
Labels: bug
